### ISSUE TITLE
The int->float conversion constant is 32786, should probably be 32768

### ISSUE THREAD

**Issue by sivantoledo** [rigexpert/libfobos#6]
https://github.com/rigexpert/libfobos/blob/ddea0e8df3db2ba97e61eba7bffd34d09f2357d3/fobos/fobos.c#L1693C5-L1694C38

The int->float conversion constant is 32786, should probably be 32768. This is in both the referenced line and the one that follows. (The 32786.0 is not "wrong", but it also does not make any particular sense given that the int16 is bounded by 32768; if the 32786 is to allow for the DC offset correction etc, it might be good to explain this in a comment).

**Comment by rigexpert** [comment]
yep, thanks
