### ISSUE TITLE
Did someone succeeded build on Windows?

### ISSUE THREAD

**Issue by heroInCommunity** [rigexpert/libfobos#8]
I tried to build code on Windows, but without any luck:
 cmake -DCMAKE_CXX_COMPILER="C:\Users\test\mingw64\bin\g++.exe" -DCMAKE_C_COMPILER="C:\Users\test\mingw64\bin\gcc.exe" -G "MinGW Makefiles" ..

then when I tried to run 
cmake --build . --config Release

I got error

[ 14%] Building C object CMakeFiles/libfobos.dir/fobos/fobos.c.obj
C:\Users\test\git\libfobos\fobos\fobos.c:23:10: fatal error: libusb-1.0/libusb.h: No such file or directory
   23 | #include <libusb-1.0/libusb.h>
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
mingw32-make[2]: *** [CMakeFiles\libfobos.dir\build.make:76: CMakeFiles/libfobos.dir/fobos/fobos.c.obj] Error 1
mingw32-make[1]: *** [CMakeFiles\Makefile2:87: CMakeFiles/libfobos.dir/all] Error 2
mingw32-make: *** [Makefile:135: all] Error 2

I tried to replace #include <libusb-1.0/libusb.h> with #include <libusb.h> in fobos/fobos.c
but it lead to another error.

Are there any working instructions for Windows?

**Comment by sivantoledo** [comment]
Yes, I was able to build the library into a DLL (not the binaries in eval) using visual studio 2019 community edition, on the command line (script really, but not the IDE).

**Comment by rigexpert** [comment]
Try to download and unpack libusb content into libusb directory manualy.
The only working instructions for Windows is as in readme.md section "Windows"
