### ISSUE TITLE
macOS ARM Build

### ISSUE THREAD

**Issue by cmh716** [rigexpert/libfobos#9]
Are there any plans to support macOS ARM so we can use FoboSDR on powerful ARM Macs?

Undefined symbols for architecture arm64:
  "_libusb_alloc_transfer", referenced from:
      _fobos_alloc_buffers in fobos.c.o
  "_libusb_bulk_transfer", referenced from:
      _fobos_rx_read_sync in fobos.c.o
  "_libusb_cancel_transfer", referenced from:
      _fobos_rx_read_async in fobos.c.o
  "_libusb_claim_interface", referenced from:
      _fobos_rx_open in fobos.c.o
  "_libusb_close", referenced from:
      _fobos_rx_list_devices in fobos.c.o
      _fobos_rx_open in fobos.c.o
      _fobos_rx_close in fobos.c.o
  "_libusb_control_transfer", referenced from:
      _fobos_spi in fobos.c.o
      _fobos_spi in fobos.c.o
      _fobos_i2c_transfer in fobos.c.o
      _fobos_i2c_transfer in fobos.c.o
      _fobos_i2c_write in fobos.c.o
      _fobos_i2c_read in fobos.c.o
      _fobos_max2830_write_reg in fobos.c.o
      ...
  "_libusb_error_name", referenced from:
      _fobos_rx_read_async in fobos.c.o
  "_libusb_exit", referenced from:
      _fobos_rx_get_device_count in fobos.c.o
      _fobos_rx_list_devices in fobos.c.o
      _fobos_rx_open in fobos.c.o
      _fobos_rx_close in fobos.c.o
  "_libusb_free_device_list", referenced from:
      _fobos_rx_get_device_count in fobos.c.o
      _fobos_rx_list_devices in fobos.c.o
      _fobos_rx_open in fobos.c.o
  "_libusb_free_transfer", referenced from:
      _fobos_free_buffers in fobos.c.o
  "_libusb_get_device_descriptor", referenced from:
      _fobos_rx_get_device_count in fobos.c.o
      _fobos_rx_list_devices in fobos.c.o
      _fobos_rx_open in fobos.c.o
  "_libusb_get_device_list", referenced from:
      _fobos_rx_get_device_count in fobos.c.o
      _fobos_rx_list_devices in fobos.c.o
      _fobos_rx_open in fobos.c.o
  "_libusb_get_string_descriptor_ascii", referenced from:
      _fobos_rx_list_devices in fobos.c.o
      _fobos_rx_open in fobos.c.o
      _fobos_rx_open in fobos.c.o
      _fobos_rx_open in fobos.c.o
  "_libusb_handle_events_timeout_completed", referenced from:
      _fobos_rx_read_async in fobos.c.o
      _fobos_rx_read_async in fobos.c.o
      _fobos_rx_read_async in fobos.c.o
  "_libusb_init", referenced from:
      _fobos_rx_get_device_count in fobos.c.o
      _fobos_rx_list_devices in fobos.c.o
      _fobos_rx_open in fobos.c.o
  "_libusb_open", referenced from:
      _fobos_rx_list_devices in fobos.c.o
      _fobos_rx_open in fobos.c.o
  "_libusb_submit_transfer", referenced from:
      _fobos_rx_read_async in fobos.c.o
      __libusb_callback in fobos.c.o
ld: symbol(s) not found for architecture arm64
cc: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [libfobos.dylib] Error 1
make[1]: *** [CMakeFiles/libfobos.dir/all] Error 2
make: *** [all] Error 2

**Comment by rigexpert** [comment]
It seams you have not libusb installed properly. Please refer to https://stackoverflow.com/questions/3853634/how-to-set-up-libusb-on-mac-os-x
